# Site settings
title: Joseph Weber | Web Developer
email: wosephjeber@gmail.com
description: Web developer, graphic designer, photographer. I blog about web development occasionally.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wosephjeber.github.io" # the base hostname & protocol for your site
twitter_username: wosephjeber
github_username:  wosephjeber

permalink: /blog/:title

# Build settings
markdown: kramdown

exclude: [node_modules, Gruntfile.js, package.json, hero-background.psd, Gemfile, Gemfile.lock]

# Tag pages
tag_page_layout: tags
tag_page_dir: tag
tag_permalink_style: pretty
